package com.indivaragroup.woi.mobile.awsgateway.constant;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorConstant {
    SUCCESS("00", "Success"),
    PENDING("01", ""),
    FAILED("02", ""),

    SUCCESS_BILLER("000", "Transaction Success"),
    PENDING_BILLER("002", "Transaction Suspect, Please Contact Customer Service"),
    FAILED_BILLER("201", "Transaction Failed"),

    ACCOUNT_EMPTY("01", "Account Empty"),
    ACCOUNT_INVALID("02", "Invalid Account"),
    ACCOUNT_EXPIRED("02E", "Account is Expired"),
    INPUT_ACCOUNT_NUMBER("03", "Please input account number"),
    INVALID_DEST_ACCOUNT("05", "Invalid Destination Account"),
    BOTH_ACCOUNT_SIMILAR("06", "Destination Account Number cannot be the same as your Account Number"),
    SECURITY_KEY_FALSE("07", "You’ve entered an incorrect MPIN, Please try again"),
    INVALID_ISSUER("08", "Issuer is invalid"),
    PASSWORD_EMPTY("09", "Pin Empty"),
    EMAIL_EMPTY("10", "Email is empty"),
    EMAIL_INVALID("11", "email format is invalid"),
    GENDER_INVALID("12", "gender atribute is empty or not requested as M/F value"),
    CARD_STOCK_EMPTY("13", "your issuer has no stock card"),
    CARD_INVALID("14",  "Card Number is invalid for this transaction"),
    DUPLICATE_ISSUER_CARD("15", "Card with same issuer is not allowed"),
    INVALID_BIRTHDATE("16", "Invalid birthday type request, Date must be yyyy-MM-dd"),
    CARD_NUMBER_EMPTY("17", "Card Number is empty"),
    DIFFERENT_ISSUER("18", "Source and Destination has different issuer"),
    ISSUER_EMPTY("19", "Issuer is empty"),
    ACCOUNT_MUST_BE_NUMBERS("20", "Account Must Be Numbers"),
    DUPLICATE_ACCOUNT("21", "Account Duplicated"),
    ACCOUNT_TOO_SHORT("22", "Account Length Too Short"),
    INVALID_ACCOUNT_PREFIX("23", "Invalid Account Prefix"),
    NAME_EMPTY("24", "Name Empty"),
    ACCOUNT_LOCKED("25", "Account is locked"),
    DEST_ACCOUNT_TOO_SHORT("26", "Destination Account Length Too Short"),
    INVALID_DEST_ACCOUNT_PREFIX("27", "Invalid Destination Account Prefix"),
    SECURITY_QUESTION_EMPTY("28", "Security question is empty"),
    SECURITY_QUESTION_INVALID("29", "Security question is invalid"),
    SECURITY_ANSWER_EMPTY("30", "Security answer is empty"),
    SECURITY_ANSWER_WRONG("31",  "Security answer is wrong"),
    CHANNEL_EMPTY("32", ""),
    FILE_EMPTY("33", "Mandatory field is empty"),
    UPLOAD_FAILED("33", "Upload Failed"),
    INVALID_DATEFORMAT("34", "Invalid Date Format"),
    INVALID_PAYMENT_METHOD("35", "Invalid Payment Method"),
    AMOUNT_BELOW_0("41", "Amount Below 0"),
    INSUFFICIENT_BALANCE("42", "Insufficient balance"),
    TRANSFER_AMOUNT_BELOW_MIN("43", "Transfer Amount Below Minimum Fund Transfer"),
    TRANSFER_AMOUNT_ABOVE_MAX("44", "Transfer Amount Above Maximum Fund Transfer"),
    BALANCE_AFTER_TRANSFER_BELOW_MIN("45", "You don't have enough funds"),
    BALANCE_AFTER_TRANSFER_ABOVE_MAX_ADD_MONEY("46", "The Amount you input will exceed your eWallet limit"),
    BALANCE_AFTER_TRANSFER_ABOVE_MAX_TRANSFER("46B", "Wallet balance of the receiver after transaction will exceed the maximum allowed balance"),
    TRX_AMOUNT_EXCEEDED_DAILY("47", "Transaction Amount Exceed Daily Maximum Transaction Amount"),
    TRX_COUNT_EXCEEDED_DAILY("48", "Transaction Exceed Daily Maximum Transaction Count"),
    OTP_EXPIRED("50", "Your One-Time PIN has expired. Please try again after 5 minutes"),
    INVALID_TRX_DATE("51", "Not Valid Transaction Date for Organization"),
    INVALID_TRX_ID("52", "Transaction ID is invalid"),
    AMOUNT_EMPTY("53", "Amount is empty"),
    INVALID_STORE("54", "Store is invalid"),
    TERMINAL_ID_EMPTY("55", "Terminal is empty"),
    STORE_ID_EMPTY("56", "Store is empty"),
    TRANSACTION_ID_EMPTY("57", "Transaction ID is empty"),
    DUPLICATE_TRX_ID("58", "Transaction ID is duplicate with different transaction"),
    INVALID_OTP("59", "OTP code is invalid"),
    INVALID_TRX_TYPE("60", "Transaction Type is Invalid"),
    INVALID_STATUS("61", "Transaction Status is Invalid"),
    INVALID_REFNUMBER("62", "Transaction Not Found"),
    INVALID_BILLERCODE("63", "BillerCode is invalid"),
    EMPTY_BILLERCODE("64", "BillerCode Empty"),
    CANT_DO_PROCESS("65", "Request Can't be Processed."),
    INTERNAL_SERVER_ERROR("66", "Internal Server Error"),
    BANK_NOT_SUPPORTED("71", "Bank code not supported"),
    AMOUNT_NOT_PASSING_DENOMINATION("72", "Amount's Remainder Not Passing Denomination Validation"),
    CANT_SAVINGS_MONEY("77", "Cannot savings money"),
    HAVE_SAVINGS("78", "You already have savings"),
    NOT_INTEGRATED("79", "Not integrated"),
    INVALID_TERMINAL("80", "Terminal is invalid for this store"),
    MERCHANT_CODE_EMPTY("81", "Merchant Code was Empty"),
    MERCHANT_CODE_INVALID("82", "Invalid Merchant Code"),
    ORDER_ID_EMPTY("83", "Order Id was Empty"),
    ORDER_NOT_FOUND("84", "Order not Found, Please re-check the order details"),
    ORDER_HAS_BEEN_PAID("85", "Order has been paid"),
    ORDER_WAS_EXPIRED("86", "Order was expired"),
    INVALID_EVENT("87", "Event for this transaction is not found or expired"),
    DUPLICATE_ACTIVITY_ID("88", "Activity ID is duplicate with different activity change"),
    DEST_ACCOUNT_EXIST("89", "Destination Account is already exist"),
    INVALID_ACTIVITY_ID("90", "Activity ID is invalid"),
    SEND_EMAIL_FAILED("91", "Fail to send e-mail"),
    IDENTIFICATION_NO_INVALID("92", "Invalid identification number"),
    SEND_EMAIL_FAILED_BUT_REG_OK("93", "Send email failed, but registration succeeded"),
    SEND_SMS_ERROR("94", "Send Sms Error"),
    INVALID_LIVING_ADDRESS("95", "Living address incorrect"),
    INVALID_NATIONALITY("96", "Nationality incorrect"),
    INVALID_JOB("97", "Job incorrect"),
    INVALID_TOKEN("98", "Invalid Token"),
    ERROR_LOYALTY("99", "Sorry, Internal system error."),
    LOYALTY_ACCESS("100", "Your issuer has no loyalty support"),
    DEST_ACCOUNT_EMPTY("101", "Destination account is empty"),
    DEST_ACCOUNT_LOCKED("102", "Destination account is locked"),
    LITE_ACCOUNT_UNAUTHORIZED("103", "Member needs to be above LITE status to use this feature"),
    MERCHANT_EMPTY("103", "List Merchant Empty"),
    CWATM_INSUFFICIENT_BALANCE("104", "You don't have enough funds."),
    INVALID_NOTIF_TRX("104", "Notif transaction is not allowed"),
    INSUFFICIENT_BALANCE_AND_POINT_CANNOT_BE_ACCESSED("105", "Insufficient Balance and Point Can't Be Accessed"),
    INSUFFICIENT_BALANCE_OR_POINT("106", "Insufficient Balance or Point"),
    MERCHANT_ID_EMPTY("107", "Merchant ID is empty"),
    MERCHANT_ID_INVALID("108", "Invalid Merchant ID"),
    INSUFFICIENT_POINT("109", "Insufficient points"),
    INSUFFICIENT_BALANCE_AND_POINT("110", "Insufficient Balance and Point"),
    QR_CODE_EMPTY("111", "QR Code is empty"),
    QR_CODE_INVALID("112", "This QR Code is not supported by BPI eWallet. Please scan another code."),
    EMAIL_LOYALTY_EXIST("113", "Email already exists."),
    PHONE_NUMBER_LOYALTY_EXIST("114", "Phone number already exists."),
    INSUFFICIENT_STOCK_REWARD("115", "Insufficient Stock"),
    ADD_CARD_MERCHANT_FIRST("116", "Please add loyalty card this merchant first"),
    SIGNATURE_EMPTY("117", "Signature is empty"),
    SIGNATURE_INVALID("118", "Signature is invalid"),
    NAME_INVALID("119", "Name is invalid"),
    TRANSACTION_INVALID("120", "Transaction is invalid"),
    AMOUNT_CONTAIN_NOT_NUMBER("121", "Amount contain not number"),
    MEMBER_NOT_FOUND("122", "Member not found"),
    DESTINATION_ACCOUNT_NOT_FOUND("122D", "Invalid Destination Account"),
    INVALID_DESTINATION_SAME_NUMBER("122E", "Destination account number cannot be the same as your account number"),
    LIMIT_TRFPOINT("123", "Try again later. Transfer point to destination member not allowed"),
    VOUCHER_NOT_FOUND("124", "Voucher not found"),
    LIMIT_TRFPOINT_GOODIE("125", "Transfer point has reached the limit"),
    BILL_HAS_BEEN_PAID("126", "Bill has been paid"),
    TRANSACTION_PROCESS("127", "Your transaction in process"),
    PHONE_NUMBER_INVALID("128", "Invalid phone number"),
    TRANSACTON_BILL_FAILED("129", "Transaction failed"),
    EMAIL_REFERRAL_AND_DESTINATION_ACCOUNT_INVALID("130", "Choose one field to fill between destination account and email referral"),
    MEMBER_ALREADY_EXIST("131", "Member Already Exist"),
    INVALID_ACCOUNT("133", "Invalid Account"),
    INACTIVE_ACCOUNT("134", "Inactive Account"),
    NOT_AUTHORIZE("135", "Not Authorized"),
    MERCHANT_NOT_REGISTERED("136", "Merchant Not Registered On Issuer"),
    INVALID_REFERRAL_NUMBER("137", "Invalid Referral Number"),
    STATUS_EMPTY("138", "Status is empty"),
    ORG_LOYALITY_CODE_EMPTY("139", "Organization Loyality Code is empty"),
    SOME_ACCOUNT_LOCKED("140", "Sorry, some of your account are locked"),
    INVALID_BANK_ACCOUNT_NAME("141", "Your bank account name must be the same as your account name"),
    SUBCODE_NOT_FOUND("142", "Organization not registered"),
    ORG_MEMBER_NOT_FOUND("143", "Organization Member not found"),
    ORG_UNIT_NOT_FOUND("144", "Organization Unit not found"),
    REFERRAL_CODE_INVALID("145", "Referral code invalid."),
    CVV_EMPTY("146", "Referral code invalid"),
    EXPIRY_DATE_EMPTY("147", "Expiry Date Empty"),
    TOKEN_EMPTY("148", "Token Empty"),
    CARD_NUMBER_ALREADY_EXIST("149", "Card Number Already Exist"),
    CARD_NUMBER_REQUEST_NOT_FOUND("150", "Request Card Number Not Found"),
    CARD_NUMBER_NOT_FOUND("151", "Card Number Not Found"),
    CLOSED_ACCOUNT("152", "Your account has been closed"),
    INVALID_REQUEST("153", "Invalid Request"),
    MAX_SIZE_UPLOAD("154", "image size cannot be more than 5MB"),
    REQ_MONEY_ALREADY_PROCESS("156", "You have already paid this Request Money"),
    AD_PROMOTION_CODE_EMPTY("157", "Advertising promotion code is empty"),
    BANK_ACCOUNT_EMPTY("158", "Bank Account is Empty"),
    ACCOUNT_INVALID_LOYALTY("159", "Invalid account on loyalty system"),
    DATA_NOT_FOUND("160", "Data not found"),
    SAME_PASSWORD("161", "Old password and new password are the same"),
    N_RECORD_EMPTY("162", "N Records is empty"),
    REWARD_CAN_REDEEM_EMPTY("163", "Reward can redeem is empty"),
    VOUCHER_EMPTY("164", "Voucher is empty"),
    WRONG_PASSWORD("165", "Pin is wrong"),
    TYPE_EMPTY("166", "Pin is wrong"),
    POINT_EMPTY("167", "Point is empty"),
    ACTION_EMPTY("168", "Action is empty"),
    ONE_OR_MORE_REWARD_INVALID("169", "One or more reward is invalid"),
    REWARD_REDEEM_ONCE("170", "Reward can only be redeemed once"),
    REWARD_REDEEM_ONCE_A_DAY("171", "Reward can only be redeemed once a day"),
    CANT_GENERATE_NEW_OTP("172", "A previous process is currently active. Please wait 5 mins and try again"),
    ERROR_BPI("173", "Request cannot be processed this time"),
    INVALID_ACCOUNT_NUMBER("174", "You need to upgrade your VYBE account before you can send to bank."),
    PARSE_MERCHANT_DATA("175", "Parsed merchant data is empty"),
    SCANTOPAY_INITIATE_ERROR("176", "Scan To Pay Initiate Error"),
    QR_CODE_INVALID_AMOUNT("177", "This QR has in invalid Amount to Pay. Please scan another code."),
    INVALID_PLATFORM("178", ""),
    INVALID_OTP_VYBE("179", "You have entered an invalid OTP. Please try again"),
    INVALID_OTP_VYBE_SUSPEND("180", "We are unable to process your transaction at this time. Your One-Time PIN has been suspended after 3 invalid attempts. Please try again after 10 minutes"),
    CWATM_AMOUNT_NOT_MULTIPLES_OF_500("181", "Withdrawal amount should be in multiples of PHP 500 only."),
    CWATM_AMOUNT_BELOW_MINIMUM("182", "Amount entered is below the minimum withdrawal limit (PHP 500.00)."),
    CWATM_AMOUNT_ABOVE_MAXIMUM("183", "Amount entered exceeds the maximum withdrawal limit (PHP 10.000.00)."),
    REFERENCE_NUMBER("184", "Reference Number is Empty"),
    ECPAY_DOUBLE_TRANSACTION("185", "Transaction cannot be processed. System detects this to be a double transaction."),
    BAYAD_MINIMUM_AMOUNT("186", "Oops! Minimum amount due must be at least P5.00. Don't worry, any excess amount will be carried over on your next billing statement. Note that paying the allowed minimum amount does not waive your account of possible disconnections. Kindly ensure you settle your full amount due by your due date to avoid any inconveniences."),
    ECPAY_MISSING_PARAMETERS("187", "Missing parameters"),
    ECPAY_INVALID_AMOUNT("188", "Invalid Amount"),
    ECPAY_UNAVAILABLE_TELCO("189", "Telco is not available"),
    BAYAD_MAX_TRANS("190", "Uh oh! Your account has already reached maximum transactions with us for this month. To continue with your transaction, you may pay via the Meralco Mobile App, Meralco Online, or any Meralco Business Center near you. Thank you!"),
    PAYBILLS_ENTER_VALID_ACCOUNT("191", "Please enter a valid account number"),
    ACCOUNT_NUMBER_LIMIT_REACHED("192", "Character limit reached for Account Number."),
    ECPAY_INVALID_BILLER_CODE("193", "Invalid biller code"),
    ECPAY_INACTIVE_BILLER("194", "Biller is currently inactive"),
    CWATM_ONGOING_TRANSACTION("196", "An ongoing cash out has been requested. We're only allowing 1 cash out request at a time."),
    RM_EXIST("197", "Unable to Create VYBE Account"),
    DATE_EMPTY("198", "Date is empty please input date"),
    INVALID_AMOUNT_B_21("199", "Invalid Amount. Please enter a valid amount to pay. (B-21)"),
    UNSUCCESSFUL_CASHOUT_P2M("200", "For assistance, please call +632 889 10000."),
    INVALID_ACCOUNT_NO_E_400_3("202", "Invalid Account Number. Please enter a valid Account Number and try again. (E-400-3)"),
    ACCOUNT_NUMBER_EMPTY("203", "Account Number Is Empty"),
    RECIPIENT_BANK_EMPTY("204", "Recipient Bank Is Empty"),
    INSUFFICIENT_WALLET_BALANCE("205", "Insufficient wallet balance. Please check your VYBE eWallet balance to complete this transaction."),
    INSUFFICENT_WALLET_BALANCE_P2PO("205E", "Insufficient wallet balance"),
    INVALID_ACCOUNT_DETAILS_E_400_5("206", "Invalid Account Details. Please contact your selected biller. (E-400-5)"),
    INVALID_ACCOUNT_DETAILS_E_400_6("207", "Invalid Account Details. Please contact your selected biller for more information. (E-400-6)"),
    INVALID_TRANSACTION_DETAILS_E_400_4("208", "Invalid transaction details. Please review and try again (E-400-4)"),
    INVALID_AMOUNT_E_400_7("209", "Invalid Amount. Please enter %s as your payment amount. (E-400-7)"),
    UNABLE_TO_PROCESS_E_400_2("211", "We are unable to process your transaction at this time. (E-400-2)"),
    UNABLE_TO_PROCESS_E_500("212", "We are unable to process your transaction at this time. (E-500)"),
    INVALID_DAY_DIFFERENCE("213", "Effective date to cannot be greater than 730 days from effective date from"),
    INVALID_QR_FLAG("222", "Sub must be txn or p2pqrpay"),
    SEARCH_DATA_AND_FILL_PARAMETER("223", "Please fill out the parameters and search the data first."),
    ALREADY_PROCEEDED_BALANCE_CORRECTION("224", "Balance Correction Has Already Been Proceed."),
    LOCK_THE_ACCOUNT_FIRST("225", "Lock The Account First."),

    SECURITY_KEY_EMPTY("A1", "Security Key empty"),
    TRX_AMOUNT_EXCEEDED_DAILY_DESTINATION("A15",  "Transaction Amount Exceed Daily Maximum Transaction Amount Destination Account"),
    TRX_COUNT_EXCEEDED_MONTHLY_DESTINATION("A16", "Account destination's transaction count exceeded monthly limit"),
    TRX_COUNT_EXCEEDED_DAILY_DESTINATION("A17", "Transaction Account Destination Exceed Daily Maximum Transaction Count"),
    
    TRX_AMOUNT_EXCEEDED_MONTHLY("F1", "Transaction amount exceeded monthly limit"),
    TRX_COUNT_EXCEEDED_MONTHLY("F2", "Transaction count exceeded monthly limit"),
    INVALID_AMOUNT("F3",  "Invalid Amount"),
    SCANTOPAY_INVALID_QR("F4", "This QR has Invalid Amount to Pay"),
    TOKEN_EXPIRED("F5", "BPI Online Linking Expired"),
    INVALID_BANK("F6", "Invalid Bank"),
    CANNOT_SEND_OTP("F7", "Can not send OTP. Please try again after 5 minutes."),
    INCOMPLETE_PARAMETER("F8", "Incomplete Parameter"),
    CONNECTION_TIMED_OUT("F9", ""),
    SYSTEM_IN_CUT_OFF("F10", "Cut off, please try again in several minute !"),
    ON_PROCESS("F11", "Transaction is on processing"),

    NOT_ALLOW("NA", "Not Allow"),

    INVALID_REGION("R0", "REGION NOT FOUND"),
    INVALID_PROVINCE("R1", "Invalid Province"),
    INVALID_CITY("R2", "Invalid City"),
    INVALID_DISTRICT("R3", "Invalid District"),
    INVALID_VILLAGE("R4", "Invalid Village"),
    INVALID_POSTALCODE("R5", "Invalid Postal Code"),
    
    INVALID_FILE_EXTENSIONS("U69", "Image must be JPG, JPEG, or PNG"),

    BPI_CODE_INTERNAL_ERROR("VBEIE999", "Internal Error"),
    BPI_CODE_PARTIAL_SUCCESS("VBESE001", "Partial Success"),
    BPI_CODE_SERVICE_ERROR("VBESE999", "Service Error"),
    BPI_CODE_ADDING_RMTRAILER_FAILED("VBEBE001", "Adding of product failed"),
    BPI_CODE_FAILED_NDV("VBEBE002", "Customer has data in ndv"),
    BPI_CODE_FAILED_LOGGING("VBEBE002", "Failed Logging"),
    BPI_CODE_INPUT_INVALID("VBEVE999", "The input is invalid"),

    ECPAY_PAYBILLS_400_1("400","We are unable to process your transaction at this time. (E-400-1)"),
    ECPAY_PAYBILLS_400_2("400","We are unable to process your transaction at this time. (E-400-2)"),
    ECPAY_PAYBILLS_400_3("400","Invalid Account Number. Please ented a valid Account Number and try again. (E-400-3)"),
    ECPAY_PAYBILLS_400_4("400","Invalid transaction details. Please review and try again. (E-400-4)"),
    ECPAY_PAYBILLS_400_5("400","Invalid Account Details. Please contact your selected biller. (E-400-5)"),
    ECPAY_PAYBILLS_400_6("400","Invalid Account Details. Please contact your selected biller for more information. (E-400-6)"),
    ECPAY_PAYBIILS_400_7("400","Invalid Amount. Please enter %s as your payment amount. (E-400-7)"),
    ECPAY_PAYBILLS_400_8("400","Invalid Amount. Please enter %s or %s as your payment amount. (E-400-8)"),
    ECPAY_PAYBILLS_400_9("400","Invalid Amount. Minimum amount should be %s. (E-400-9)"),
    ECPAY_PAYBILLS_400_10("400","We are unable to process your transaction at this time. Please try again. (E-400-10)"),
    ECPAY_PAYBILLS_400_11("400","We are unable to process your transaction. (E-400-11)"),
    ECPAY_PAYBILLS_400_12("400","We are unable to process your transaction. (E-400-12)"),
    ECPAY_PAYBILLS_400_13("400","We are unable to process your transaction. (E-400-13)"),
    ECPAY_PAYBILLS_400_14("400","Invalid Amount. Please enter a valid amount to pay. (E-400-14)"),
    ECPAY_PAYBILLS_400_15("400","We are unable to process your transaction. (E-400-15)"),
    ECPAY_PAYBILLS_400_16("400","We are unable to process your transaction. (E-400-16)"),
    ECPAY_PAYBILLS_401("401","We are unable to process your transaction at this time. (E-401)"),
    ECPAY_PAYBILLS_403("403","We are unable to process your transaction. (E-403)"),
    ECPAY_PAYBILLS_404("404","We are unable to process your transaction. (E-404)"),
    ECPAY_PAYBILLS_422("422","We are unable to process your transaction. (E-422)"),
    ECPAY_PAYBILLS_422_1("422","We are unable to process your transaction. (E-422-1)"),
    ECPAY_PAYBILLS_422_2("422","We are unable to process your transaction. (E-422-2)"),
    ECPAY_PAYBILLS_422_3("422","Invalid Amount. Please enter a valid amount to pay. (E-422-3)");

    private final String code;
    private final String message;
}
