baseUrl: ${MOBILE_BASE_URL}
baseUrlCo: ${CO_BASE_URL}
idp:
  httpClient:
    baseUrl: ${MOBILE_IDP_INTERNAL}/api/
    connectTimeoutInMilliseconds: 5000
    readTimeoutInMilliseconds: 5000
    logLevel: BODY
cardlessWithdrawal:
  httpClient:
    baseUrl: ${MOBILE_CARDLESS_WITHDRAWAL_INTERNAL:https://woi-mobile-api.indivaragroup.com/${co.code}/transaction-cardless-withdrawal}/api/
    connectTimeoutInMilliseconds: 15000
    readTimeoutInMilliseconds: 15000
    logLevel: BODY
qris:
  httpClient:
    baseUrl: ${MOBILE_QRIS_INTERNAL}/api/
    connectTimeoutInMilliseconds: 60000
    readTimeoutInMilliseconds: 60000
    logLevel: BODY
biSnap:
  httpClient:
    baseUrl: ${CO_MERCHANT_INTERNAL}/api/
    connectTimeoutInMilliseconds: 15000
    readTimeoutInMilliseconds: 15000
    logLevel: BODY
bayarGw:
  merchantId: ${BAYAR_GW_MERCHANT_ID}
  transactionKey: ${BAYAR_GW_TRANSACTION_KEY}
algoCardlessWithdrawal:
  clientId: ${ALGO_CLIENT_ID:067b5c25-3d8e-49a7-84fc-13faae01f302}
  partnerId: ${ALGO_PARTNER_ID:067b5c25-3d8e-49a7-84fc-13faae01f302}
  secretId: ${ALGO_SECRET_ID:ZQHA35Gv0rY1u6gdKefIX7z8DL9k2o4b}
  channelId: ${ALGO_CHANNEL_ID:75421}
  encodedPublicKey: ${ALGO_ENCODED_PUBLIC_KEY:LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6M0FSWXV3dmcxcFN6cDdQdC95eQpzc3pIeUlWbGx3azRVV1pCdDd4em9vQjhtMUJYMlRaeFRrRXc4MUx5QTVvbkEzbmlQclcvLy9XNWZtL3RZRitTCjRTV25GcTNXMmVuWis4ZDhZK0dHdUNTRndiQ0h6R2xhYU9USDBic0NtRkRCek9IcjlybUt3YTBFcFNnWHZTVGIKUUsvRzJuRloxN3hBYVZGZ2ZXNjREVDZrTjFMMldtMDBDUmZ2Vk9ZZThPc21YeXl2Ky8zdFdLZVJmTlE4MkJnZQpnWHVWMlhkYnV0dFVnandCVnBqTncwY0MrTEYvTnBOcmhlbkRQNEt1aVBoNTIrUWQ1R01VdVlXZVNiNmxUTVlZCjFTZWxmaWpsdi9KcnBFekJTMHVJZ1FmaDhPSklLaHgrbXRpekVHdEg2SXlOZWh2TUFrQnh0OFJram5yM1FZcFUKZndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==}
biller:
  sourceId: ${BILLER_SOURCE_ID:1}
  sourceUser: ${BILLER_SOURCE_USER:astra}
  sourcePass: ${BILLER_SOURCE_PASS:astra}
rintis:
  clientId: ${RINTIS_HTTP_CLIENT_CLIENT_ID}
  clientSecret: ${RINTIS_HTTP_CLIENT_CLIENT_SECRET}
  partnerId: ${RINTIS_PARTNER_ID:INDIVARA-2010360844}
  secretId: ${RINTIS_SECRET_ID:42af0db790a78b1a4ca010384f3a9e9b82d90c06db64fee7236bb1964a1e221ed6ade208f18d4e5e65e90de4c7d0d21beb0b67b425195aad53393a3ffc967186}
co:
  code: ${CO_APP_CODE:woi}