baseUrl: https://woi-mobile-api-dev.indivaragroup.com
baseUrlCo: https://woi-co-api-dev.indivaragroup.com
idp:
  httpClient:
    baseUrl: https://woi-mobile-api-dev.indivaragroup.com/${co.code}/idp/api/
    connectTimeoutInMilliseconds: 15000
    readTimeoutInMilliseconds: 15000
    logLevel: BODY
cardlessWithdrawal:
  httpClient:
    baseUrl: https://woi-mobile-api-dev.indivaragroup.com/${co.code}/transaction-cardless-withdrawal/api/
    connectTimeoutInMilliseconds: 15000
    readTimeoutInMilliseconds: 15000
    logLevel: BODY
qris:
  httpClient:
    baseUrl: https://woi-mobile-api-dev.indivaragroup.com/${co.code}/transaction-qris/api/
    connectTimeoutInMilliseconds: 60000
    readTimeoutInMilliseconds: 60000
    logLevel: BODY
biSnap:
  httpClient:
    baseUrl: https://woi-co-api-dev.indivaragroup.com/${co.code}/merchant/api/
    connectTimeoutInMilliseconds: 15000
    readTimeoutInMilliseconds: 15000
    logLevel: BODY
bayarGw:
  merchantId: WOI2S
  transactionKey: woi##woipass
algoCardlessWithdrawal:
  clientId: 067b5c25-3d8e-49a7-84fc-13faae01f302
  partnerId: 067b5c25-3d8e-49a7-84fc-13faae01f302
  secretId: ZQHA35Gv0rY1u6gdKefIX7z8DL9k2o4b
  channelId: 75421
  encodedPublicKey : LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6M0FSWXV3dmcxcFN6cDdQdC95eQpzc3pIeUlWbGx3azRVV1pCdDd4em9vQjhtMUJYMlRaeFRrRXc4MUx5QTVvbkEzbmlQclcvLy9XNWZtL3RZRitTCjRTV25GcTNXMmVuWis4ZDhZK0dHdUNTRndiQ0h6R2xhYU9USDBic0NtRkRCek9IcjlybUt3YTBFcFNnWHZTVGIKUUsvRzJuRloxN3hBYVZGZ2ZXNjREVDZrTjFMMldtMDBDUmZ2Vk9ZZThPc21YeXl2Ky8zdFdLZVJmTlE4MkJnZQpnWHVWMlhkYnV0dFVnandCVnBqTncwY0MrTEYvTnBOcmhlbkRQNEt1aVBoNTIrUWQ1R01VdVlXZVNiNmxUTVlZCjFTZWxmaWpsdi9KcnBFekJTMHVJZ1FmaDhPSklLaHgrbXRpekVHdEg2SXlOZWh2TUFrQnh0OFJram5yM1FZcFUKZndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
biller:
  sourceId: 1
  sourceUser: astra
  sourcePass: astra
rintis:
  clientId: 8c215954-c30d-4fa5-b2e9-97da8f98052a
  clientSecret: 92edfa0c-280f-46b6-8bb8-427c9f1c114a
  partnerId: INDIVARA-2010360844
  secretId: 42af0db790a78b1a4ca010384f3a9e9b82d90c06db64fee7236bb1964a1e221ed6ade208f18d4e5e65e90de4c7d0d21beb0b67b425195aad53393a3ffc967186
